# Generated by Django 5.1 on 2024-09-09 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('practical', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_record.class', verbose_name='class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(unique=True)),
                ('student_class', models.ForeignKey(db_column='class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_record.class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Theory Marks')),
                ('pr', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Practical Marks')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_record.classsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='student_record.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subject_scores',
            field=models.ManyToManyField(through='student_record.StudentSubject', to='student_record.classsubject'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('credit_hours', models.FloatField()),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_record.marks')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_record.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_record.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', through='student_record.ClassSubject', to='student_record.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_record.teacher'),
        ),
        migrations.AddConstraint(
            model_name='studentsubject',
            constraint=models.UniqueConstraint(models.F('class_subject'), models.F('student'), name='unique_student_subject'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(models.F('grade'), models.F('section'), name='unique_class'),
        ),
    ]
