# Generated by Django 5.1 on 2024-09-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit_hours',
            field=models.FloatField(),
        ),
    ]
