# Generated by Django 5.1 on 2024-09-03 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_record", "0002_alter_student_roll_alter_subject_credit_hours"),
    ]

    operations = [
        migrations.RenameField(
            model_name="StudentSubject",
            old_name="obtained_marks_theory",
            new_name="th",
        ),
        migrations.RenameField(
            model_name="StudentSubject",
            old_name="obtained_marks_practical",
            new_name="pr",
        ),
    ]
