# Generated by Django 5.1 on 2024-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0002_electivesubjectgroup_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentsubject',
            constraint=models.UniqueConstraint(models.F('subject'), models.F('student'), name='unique_student_subject'),
        ),
    ]
