# Generated by Django 5.1 on 2024-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0003_update_th_pr_field_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='pr',
            field=models.IntegerField(verbose_name='Practical Marks'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='th',
            field=models.IntegerField(verbose_name='Theory Marks'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practical_marks',
            field=models.IntegerField(default=0),
        ),
    ]
