# Generated by Django 5.1 on 2024-09-03 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0004_alter_studentsubject_pr_alter_studentsubject_th_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='pr',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Practical Marks'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='th',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Theory Marks'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practical_marks',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='theory_marks',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
