# Generated by Django 5.1 on 2024-09-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0004_remove_subject_elective_group_alter_student_class_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField()),
                ('percentage', models.FloatField()),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=100)),
                ('remarks', models.TextField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_record.class', verbose_name='Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_record.student')),
            ],
        ),
    ]
