# Generated by Django 5.1 on 2024-09-11 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0005_marksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_marks', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('full_marks', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
