# Generated by Django 5.1 on 2024-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0005_alter_studentsubject_pr_alter_studentsubject_th_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
