# Generated by Django 5.1 on 2024-09-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0006_marksclassification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='practical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical', to='student_record.marksclassification'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory', to='student_record.marksclassification'),
        ),
    ]
