# Generated by Django 5.1 on 2024-09-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0007_subject_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
