# Generated by Django 5.1 on 2024-09-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0007_alter_marks_practical_alter_marks_theory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject_scores',
            new_name='subjects',
        ),
    ]
