# Generated by Django 5.1 on 2024-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0008_rename_subject_scores_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='total',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
