# Generated by Django 5.1 on 2024-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0009_studentsubject_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
