# Generated by Django 5.1 on 2024-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0010_alter_marksheet_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='exam_type',
            field=models.CharField(default='board', max_length=100),
        ),
    ]
