# Generated by Django 5.1 on 2024-09-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0010_alter_marks_using_marks_table_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_record.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(db_column='class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_record.class'),
        ),
    ]
