# Generated by Django 5.1 on 2024-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0011_marksheet_exam_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marksheet',
            constraint=models.UniqueConstraint(fields=('student', 'class_id', 'exam_type'), name='unique_marksheet'),
        ),
    ]
