# Generated by Django 5.1 on 2024-09-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0011_remove_student_grade_class_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(models.F('grade'), models.F('section'), name='unique_class'),
        ),
    ]
