# Generated by Django 5.1 on 2024-09-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0012_marksheet_unique_marksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivestudentsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_record.subject'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='exam_type',
            field=models.CharField(choices=[('board', 'Board'), ('terminal', 'Terminal')], default='board', max_length=100),
        ),
    ]
