# Generated by Django 5.1 on 2024-09-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0012_class_section_class_unique_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
