# Generated by Django 5.1 on 2024-09-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_record", "0013_remove_student_section"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(default=" ", max_length=255),
            preserve_default=False,
        ),
    ]
