# Generated by Django 5.1 on 2024-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0014_replace_teacher_name_too_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
