# Generated by Django 5.1 on 2024-09-06 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0015_alter_teacher_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='th',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Theory Marks'),
        ),
    ]
